### ISSUE TITLE
geoviews can't currently be imported on travis?

### ISSUE THREAD

**Issue by ceball** [ioam/geoviews#109]
Was making some website edits...

<img width="1060" alt="screen shot 2017-12-11 at 3 07 30 pm" src="https://user-images.githubusercontent.com/1929/33837694-19fa7c72-de85-11e7-9fbc-b26017a9f5dd.png">

**Comment by ceball** [comment]
I ran the following on macos 10.12.6 and didn't get that problem. Of course, I got a different problem:

```
$ conda create -n geov2 python=3.6* nose numpy matplotlib bokeh pandas scipy jupyter ipython param flake8 mock filelock
$ source activate geov2
$ conda install -c conda-forge holoviews iris cartopy xarray geopandas numpy=1.13.3
$ pip install -e .
$ python -c "import geoviews"
$ nosetests --with-doctest --with-coverage --cover-package=geoviews
nose.plugins.cover: ERROR: Coverage not available: unable to import coverage module
E/Users/cball/Eunectes/mc3/envs/geov2/lib/python3.6/site-packages/iris/tests/__init__.py:79: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'MacOSX' by the following code:
  File "/Users/cball/Eunectes/mc3/envs/geov2/bin/nosetests", line 11, in <module>
    sys.exit(run_exit())
  File "/Users/cball/Eunectes/mc3/envs/geov2/lib/python3.6/site-packages/nose/core.py", line 121, in __init__
    **extra_args)
  File "/Users/cball/Eunectes/mc3/envs/geov2/lib/python3.6/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/Users/cball/Eunectes/mc3/envs/geov2/lib/python3.6/site-packages/nose/core.py", line 207, in runTests
    result = self.testRunner.run(self.test)
  File "/Users/cball/Eunectes/mc3/envs/geov2/lib/python3.6/site-packages/nose/core.py", line 62, in run
    test(result)
  File "/Users/cball/Eunectes/mc3/envs/geov2/lib/python3.6/site-packages/nose/suite.py", line 177, in __call__
    return self.run(*arg, **kw)
  File "/Users/cball/Eunectes/mc3/envs/geov2/lib/python3.6/site-packages/nose/suite.py", line 224, in run
    test(orig)
  File "/Users/cball/Eunectes/mc3/envs/geov2/lib/python3.6/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/Users/cball/Eunectes/mc3/envs/geov2/lib/python3.6/site-packages/nose/suite.py", line 72, in run
    for test in self._tests:
  File "/Users/cball/Eunectes/mc3/envs/geov2/lib/python3.6/site-packages/nose/suite.py", line 99, in _get_tests
    for test in self.test_generator:
  File "/Users/cball/Eunectes/mc3/envs/geov2/lib/python3.6/site-packages/nose/loader.py", line 191, in loadTestsFromDir
    entry_path, discovered=True)
  File "/Users/cball/Eunectes/mc3/envs/geov2/lib/python3.6/site-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/cball/Eunectes/mc3/envs/geov2/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/cball/Eunectes/mc3/envs/geov2/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/cball/Eunectes/mc3/envs/geov2/lib/python3.6/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/Users/cball/Eunectes/mc3/envs/geov2/lib/python3.6/imp.py", line 217, in load_package
    return _load(spec)
  File "/Users/cball/code/ioam/geoviews/geoviews/__init__.py", line 15, in <module>
    from . import plotting                              # noqa (API import)
  File "/Users/cball/code/ioam/geoviews/geoviews/plotting/__init__.py", line 1, in <module>
    from . import mpl # noqa
  File "/Users/cball/code/ioam/geoviews/geoviews/plotting/mpl/__init__.py", line 17, in <module>
    from holoviews.plotting.mpl import (ElementPlot, ColorbarPlot, PointPlot,
  File "/Users/cball/Eunectes/mc3/envs/geov2/lib/python3.6/site-packages/holoviews/plotting/mpl/__init__.py", line 12, in <module>
    from .annotation import * # noqa (API import)
  File "/Users/cball/Eunectes/mc3/envs/geov2/lib/python3.6/site-packages/holoviews/plotting/mpl/annotation.py", line 6, in <module>
    from .element import ElementPlot
  File "/Users/cball/Eunectes/mc3/envs/geov2/lib/python3.6/site-packages/holoviews/plotting/mpl/element.py", line 6, in <module>
    import matplotlib.pyplot as plt
  File "/Users/cball/Eunectes/mc3/envs/geov2/lib/python3.6/site-packages/matplotlib/pyplot.py", line 69, in <module>
    from matplotlib.backends import pylab_setup
  File "/Users/cball/Eunectes/mc3/envs/geov2/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 14, in <module>
    line for line in traceback.format_stack()


  matplotlib.use('agg')
...
======================================================================
ERROR: Failure: ImportError (dlopen(/Users/cball/Eunectes/mc3/envs/geov2/lib/python3.6/site-packages/fiona/ogrext.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libuuid.1.dylib
  Referenced from: /Users/cball/Eunectes/mc3/envs/geov2/lib/libgdal.20.dylib
  Reason: image not found)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/cball/Eunectes/mc3/envs/geov2/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Users/cball/Eunectes/mc3/envs/geov2/lib/python3.6/site-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/cball/Eunectes/mc3/envs/geov2/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/cball/Eunectes/mc3/envs/geov2/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/cball/Eunectes/mc3/envs/geov2/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/Users/cball/Eunectes/mc3/envs/geov2/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cball/code/ioam/geoviews/geoviews/data/geopandas.py", line 4, in <module>
    from geopandas import GeoDataFrame
  File "/Users/cball/Eunectes/mc3/envs/geov2/lib/python3.6/site-packages/geopandas/__init__.py", line 4, in <module>
    from geopandas.io.file import read_file
  File "/Users/cball/Eunectes/mc3/envs/geov2/lib/python3.6/site-packages/geopandas/io/file.py", line 3, in <module>
    import fiona
  File "/Users/cball/Eunectes/mc3/envs/geov2/lib/python3.6/site-packages/fiona/__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/Users/cball/Eunectes/mc3/envs/geov2/lib/python3.6/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: dlopen(/Users/cball/Eunectes/mc3/envs/geov2/lib/python3.6/site-packages/fiona/ogrext.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libuuid.1.dylib
  Referenced from: /Users/cball/Eunectes/mc3/envs/geov2/lib/libgdal.20.dylib
  Reason: image not found
-------------------- >> begin captured logging << --------------------
shapely.geos: DEBUG: Trying `CDLL(/Users/cball/Eunectes/mc3/envs/geov2/bin/../lib/libgeos_c.dylib)`
shapely.geos: DEBUG: Library path: '/Users/cball/Eunectes/mc3/envs/geov2/bin/../lib/libgeos_c.dylib'
shapely.geos: DEBUG: DLL: <CDLL '/Users/cball/Eunectes/mc3/envs/geov2/bin/../lib/libgeos_c.dylib', handle 7f8a6f790e30 at 0x11c4f2eb8>
shapely.geos: DEBUG: Trying `CDLL(/usr/lib/libc.dylib)`
shapely.geos: DEBUG: Library path: '/usr/lib/libc.dylib'
shapely.geos: DEBUG: DLL: <CDLL '/usr/lib/libc.dylib', handle 1114a3bb0 at 0x10f2aac88>
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 4 tests in 2.731s

FAILED (errors=1)
```

But maybe I have other stuff on this laptop that's interfering, or I didn't follow the right instructions.

**Comment by philippjfr** [comment]
Fixed in https://github.com/ioam/geoviews/pull/113 I believe, if not please reopen.
