### ISSUE TITLE
'TileRenderer' object has no attribute 'set'

### ISSUE THREAD

**Issue by andreas-h** [ioam/geoviews#51]
I'm trying to follow the [Working with Bokeh](http://geo.holoviews.org/Working_with_Bokeh.html) tutorial.  However, when I execute

    %%opts WMTS [width=450 height=250 xaxis=None yaxis=None]
    hv.NdLayout({name: gv.WMTS(wmts, extents=(0, -90, 360, 90), crs=ccrs.PlateCarree())
                for name, wmts in tiles.items()}, kdims=['Source']).cols(2)

I get the error

    Traceback (most recent call last):
    
      File "/home/eb/software/LAMOSpy/0.2-intel-2016a-Python-2.7.11/lib/python2.7/site-packages/holoviews-1.6.2-py2.7.egg/holoviews/plotting/bokeh/element.py", line 511, in initialize_plot
        self._update_glyph(glyph, properties, mapping)
    
      File "/home/eb/software/LAMOSpy/0.2-intel-2016a-Python-2.7.11/lib/python2.7/site-packages/holoviews-1.6.2-py2.7.egg/holoviews/plotting/bokeh/element.py", line 468, in _update_glyph
        glyph.set(**{k: v for k, v in merged.items()
    
    AttributeError: 'TileRenderer' object has no attribute 'set'

I'm using Geoviews 1.1.0 with HoloViews 1.6.2 and Bokeh 0.12.4.

**Comment by philippjfr** [comment]
Please see: https://github.com/ioam/geoviews/issues/49.

>I'd downgrade back to bokeh 0.12.4 and upgrade to holoviews 1.7dev7 with:

```python
conda install -c ioam/label/dev holoviews bokeh=0.12.4
```

>We'll have a new holoviews release by the end of the month.

**Comment by andreas-h** [comment]
Thanks!  I installed holoviews v1.7dev8 from Github and it works perfectly.
